# Generated by Django 3.1.2 on 2021-01-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argonautes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_maxi', models.IntegerField(default=35)),
                ('columns_number', models.IntegerField(default=3)),
            ],
        ),
    ]
