# Generated by Django 3.1.2 on 2021-01-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argonautes', '0002_applisettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applisettings',
            name='columns_number',
            field=models.IntegerField(default=3, unique=True),
        ),
        migrations.AlterField(
            model_name='applisettings',
            name='members_maxi',
            field=models.IntegerField(default=35, unique=True),
        ),
    ]
