# Generated by Django 3.1.2 on 2021-01-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argonautes', '0003_auto_20210103_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applisettings',
            name='columns_number',
            field=models.IntegerField(default=2, unique=True),
        ),
        migrations.AlterField(
            model_name='applisettings',
            name='members_maxi',
            field=models.IntegerField(default=20, unique=True),
        ),
    ]
