# Generated by Django 3.1.2 on 2021-02-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argonautes', '0005_auto_20210110_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applisettings',
            name='columns_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='applisettings',
            name='members_maxi',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
