# Generated by Django 3.1.2 on 2021-02-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argonautes', '0006_auto_20210201_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='applisettings',
            name='profile',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='applisettings',
            name='columns_number',
            field=models.IntegerField(default=3, unique=True),
        ),
        migrations.AlterField(
            model_name='applisettings',
            name='members_maxi',
            field=models.IntegerField(default=50, unique=True),
        ),
    ]
